export const OPS_META = {
  'service-desk': {
    id: 'service-desk',
    name: 'Service Desk',
    short: 'IT tickets & incidents',
    accent: '#5BA3D9',
    basePath: '/ops/service-desk',
    listPath: '/ops/service-desk/tickets',
    newPath: '/ops/service-desk/new',
    listLabel: 'Tickets',
    newLabel: 'New ticket',
    dashboardTitle: 'Service desk dashboard',
    groupTitle: 'Tickets by category',
    burnTitle: 'Sprint burn-up',
    kpi: [
      { key: 'total', label: 'Tickets this sprint' },
      { key: 'resolved', label: 'Resolved' },
      { key: 'open', label: 'Still open' },
      { key: 'completionPct', label: 'Completion', suffix: '%' },
    ],
    colors: {
      'Service Request': '#5BA3D9',
      Incident: '#E8A838',
      Access: '#7BC67E',
      Change: '#E07A9A',
      Problem: '#9B8FE8',
    },
    plural: {
      Incident: 'Incidents',
      'Service Request': 'Service requests',
      Access: 'Access',
      Change: 'Changes',
      Problem: 'Problems',
    },
  },
  'project-manager': {
    id: 'project-manager',
    name: 'Project Manager',
    short: 'Delivery & milestones',
    accent: '#7BC67E',
    basePath: '/ops/project-manager',
    listPath: '/ops/project-manager/projects',
    newPath: '/ops/project-manager/new',
    listLabel: 'Projects',
    newLabel: 'New project',
    dashboardTitle: 'Project manager dashboard',
    groupTitle: 'Projects by type',
    burnTitle: 'Sprint burn-up',
    kpi: [
      { key: 'total', label: 'Projects this sprint' },
      { key: 'resolved', label: 'Completed' },
      { key: 'open', label: 'Still active' },
      { key: 'completionPct', label: 'Completion', suffix: '%' },
    ],
    colors: {
      Implementation: '#5BA3D9',
      Support: '#E8A838',
      Internal: '#7BC67E',
      Migration: '#E07A9A',
      Audit: '#9B8FE8',
    },
    plural: {},
  },
  leads: {
    id: 'leads',
    name: 'Leads',
    short: 'Pipeline & outreach',
    accent: '#E8A838',
    basePath: '/ops/leads',
    listPath: '/ops/leads/pipeline',
    newPath: '/ops/leads/new',
    listLabel: 'Pipeline',
    newLabel: 'New lead',
    dashboardTitle: 'Leads dashboard',
    groupTitle: 'Leads by source',
    burnTitle: 'Sprint burn-up',
    kpi: [
      { key: 'total', label: 'Leads this sprint' },
      { key: 'resolved', label: 'Won' },
      { key: 'open', label: 'Open pipeline' },
      { key: 'winRate', label: 'Win rate', suffix: '%', fallbackKey: 'completionPct' },
    ],
    colors: {
      Referral: '#5BA3D9',
      Inbound: '#7BC67E',
      Outbound: '#E8A838',
      Event: '#E07A9A',
      Partner: '#9B8FE8',
    },
    plural: {},
  },
  finance: {
    id: 'finance',
    name: 'Finance',
    short: 'Cash, billing & runway',
    accent: '#5DBF9A',
    basePath: '/ops/finance',
    listPath: '/ops/finance/billing',
    newPath: '/ops/finance/settings',
    listLabel: 'Billing',
    newLabel: 'Settings',
    ownerOnly: true,
    readOnly: true,
    nav: [
      { to: '/ops/finance', label: 'Dashboard', end: true },
      { to: '/ops/finance/billing', label: 'Billing' },
      { to: '/ops/finance/payments', label: 'Payments' },
      { to: '/ops/finance/expenses', label: 'Expenses' },
      { to: '/ops/finance/assets', label: 'Assets' },
      { to: '/ops/finance/cash', label: 'Cash' },
      { to: '/ops/finance/settings', label: 'Settings' },
      { to: '/ops/finance/journal', label: 'Journal' },
      { to: '/ops/finance/notes', label: 'Notes' },
      { to: '/ops/finance/toyota-memo', label: 'Toyota memo' },
    ],
    dashboardTitle: 'Finance dashboard',
    groupTitle: 'Pipeline by status',
    burnTitle: 'Cash history',
    kpi: [],
    colors: {
      Guaranteed: '#7BC67E',
      Hopeful: '#5BA3D9',
      'At risk': '#E8A838',
      'Early stage': '#9B8FE8',
      Lost: '#8B95A8',
    },
    plural: {},
  },
};
