import dotenv from 'dotenv';
import { replaceAllTickets } from './sheetsRepo.js';

dotenv.config();

const CATEGORIES = ['Incident', 'Service Request', 'Access', 'Change', 'Problem'];
const PRIORITIES = ['Low', 'Medium', 'High', 'Critical'];
const STATUSES = ['Open', 'In Progress', 'Resolved', 'Closed'];
const ASSIGNEES = ['Alex Rivera', 'Jordan Lee', 'Sam Patel', 'Casey Nguyen', 'Morgan Blake', ''];
const REQUESTERS = [
  'Priya Shah',
  'Chris Morgan',
  'Dana Lopez',
  'Evan Brooks',
  'Fiona Chen',
  'Gabe Ortiz',
  'Hana Kim',
  'Ian Torres',
  'Jules Reed',
  'Kai Nakamura',
];

const TITLES = [
  'Cannot access VPN',
  'Laptop battery draining fast',
  'Request new software license',
  'Password reset needed',
  'Printer offline on floor 3',
  'Email delivery delays',
  'Request mailbox access',
  'Deploy staging hotfix',
  'Recurring app crash on login',
  'Monitor flickering',
  'ShareDrive permission change',
  'New hire onboarding kit',
  'Phishing email reported',
  'Database connection timeout',
  'Request SSO for vendor tool',
  'Keyboard keys sticking',
  'Zoom meetings drop audio',
  'Update firewall rule',
  'Slow file sync to OneDrive',
  'Broken docking station',
];

function pad(n) {
  return String(n).padStart(4, '0');
}

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function daysAgoISO(days, hourOffset = 10) {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - days);
  d.setUTCHours(hourOffset, Math.floor(Math.random() * 50), Math.floor(Math.random() * 50), 0);
  return d.toISOString();
}

function buildTickets(count = 40) {
  const tickets = [];

  for (let i = 1; i <= count; i++) {
    const createdDaysAgo = Math.floor(Math.random() * 20); // within ~20 days
    const createdAt = daysAgoISO(createdDaysAgo, 8 + (i % 10));

    // Bias toward a mix of statuses for a useful dashboard
    let status;
    const r = Math.random();
    if (r < 0.28) status = 'Open';
    else if (r < 0.5) status = 'In Progress';
    else if (r < 0.82) status = 'Resolved';
    else status = 'Closed';

    const updatedDaysAgo = Math.min(createdDaysAgo, Math.floor(Math.random() * (createdDaysAgo + 1)));
    const updatedAt = daysAgoISO(updatedDaysAgo, 12 + (i % 8));

    let resolvedAt = '';
    if (status === 'Resolved' || status === 'Closed') {
      const resolvedDaysAgo = Math.min(createdDaysAgo, Math.floor(Math.random() * (createdDaysAgo + 1)));
      resolvedAt = daysAgoISO(resolvedDaysAgo, 14 + (i % 6));
    }

    const category = pick(CATEGORIES);
    const priority = pick(PRIORITIES);
    const assignee =
      status === 'Open' && Math.random() < 0.4 ? '' : pick(ASSIGNEES.filter(Boolean).concat(status === 'Open' ? [''] : []));

    tickets.push({
      ID: `TCK-${pad(i)}`,
      Title: `${pick(TITLES)} (#${i})`,
      Description: `Sample ticket ${i}: ${category.toLowerCase()} related to "${pick(TITLES).toLowerCase()}". Generated by seed script.`,
      Category: category,
      Priority: priority,
      Status: status,
      Requester: pick(REQUESTERS),
      Assignee: assignee || (status === 'Open' ? '' : pick(ASSIGNEES.filter(Boolean))),
      CreatedAt: createdAt,
      UpdatedAt: updatedAt,
      ResolvedAt: resolvedAt,
    });
  }

  // Ensure we use every category/status at least once for charts
  tickets[0].Category = 'Incident';
  tickets[0].Status = 'Open';
  tickets[0].ResolvedAt = '';
  tickets[1].Category = 'Service Request';
  tickets[1].Status = 'In Progress';
  tickets[1].ResolvedAt = '';
  tickets[2].Category = 'Access';
  tickets[2].Status = 'Resolved';
  tickets[2].ResolvedAt = tickets[2].ResolvedAt || daysAgoISO(2);
  tickets[3].Category = 'Change';
  tickets[3].Status = 'Closed';
  tickets[3].ResolvedAt = tickets[3].ResolvedAt || daysAgoISO(5);
  tickets[4].Category = 'Problem';
  tickets[4].Status = 'Open';
  tickets[4].ResolvedAt = '';

  return tickets;
}

async function main() {
  console.log('Seeding Google Sheet with sample tickets...');
  const tickets = buildTickets(40);
  await replaceAllTickets(tickets);
  console.log(`Wrote ${tickets.length} tickets to the Tickets sheet.`);
  console.log(`First ID: ${tickets[0].ID}, Last ID: ${tickets[tickets.length - 1].ID}`);
}

main().catch((err) => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
